version: "3.7"

services:
  postgredb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maytheu@db
      - POSTGRES_DB=pdc
    volumes:
      - pgdata:/var/lib/postgres/data

  pdc-server:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:maytheu@db@postgredb:5432/pdc?schema=public
    ports:
      - 4002:4002
    depends_on:
      - postgredb

volumes:
  pgdata:
